### ISSUE TITLE
Unable to strip library '/home/iuri/QonteoApps/react-native-opencv3-tests/CvFaceLandmarks/android/app/build/intermediates/transforms/mergeJniLibs/debug/0/lib/mips64/libopencv_java3.so' due to missing strip tool for ABI 'MIPS64'. Packaging it as is.

### ISSUE THREAD

**Issue by qonteo** [qonteo/qonteofaces#1]
Running npx react-native run-android, returns the following error

> Task :app:transformNativeLibsWithStripDebugSymbolForDebug
Unable to strip library '/home/iuri/QonteoApps/react-native-opencv3-tests/CvFaceLandmarks/android/app/build/intermediates/transforms/mergeJniLibs/debug/0/lib/armeabi/libopencv_java3.so' due to missing strip tool for ABI 'ARMEABI'. Packaging it as is.
Unable to strip library '/home/iuri/QonteoApps/react-native-opencv3-tests/CvFaceLandmarks/android/app/build/intermediates/transforms/mergeJniLibs/debug/0/lib/mips/libopencv_java3.so' due to missing strip tool for ABI 'MIPS'. Packaging it as is.
Unable to strip library '/home/iuri/QonteoApps/react-native-opencv3-tests/CvFaceLandmarks/android/app/build/intermediates/transforms/mergeJniLibs/debug/0/lib/mips64/libopencv_java3.so' due to missing strip tool for ABI 'MIPS64'. Packaging it as is.

> Task :app:installDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
66 actionable tasks: 66 executed
Note: /home/iuri/QonteoApps/react-native-opencv3-tests/CvFaceLandmarks/node_modules/react-native-fs/android/src/main/java/com/rnfs/RNFSManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: No connected devices!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 13s

error Failed to install the app. Make sure you have an Android emulator running or a device connected. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Note: /home/iuri/QonteoApps/react-native-opencv3-tests/CvFaceLandmarks/node_modules/react-native-fs/android/src/main/java/com/rnfs/RNFSManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: No connected devices!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 13s

    at checkExecSyncError (child_process.js:630:11)
    at execFileSync (child_process.js:648:15)
    at runOnAllDevices (/home/iuri/QonteoApps/react-native-opencv3-tests/CvFaceLandmarks/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:74:39)
    at buildAndRun (/home/iuri/QonteoApps/react-native-opencv3-tests/CvFaceLandmarks/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at /home/iuri/QonteoApps/react-native-opencv3-tests/CvFaceLandmarks/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.handleAction (/home/iuri/QonteoApps/react-native-opencv3-tests/CvFaceLandmarks/node_modules/react-native/node_modules/@react-native-community/cli/build/cliEntry.js:160:7)

**Comment by qonteo** [comment]
Updating NDK seems to be a solution 

https://stackoverflow.com/questions/53437653/android-studio-missing-strip-tool

**Comment by qonteo** [comment]
Enabling gradle.properties to multidex arch solved the problem

Within <homedir>/android/gradle/wrapper/gradle-wrapper.properties 
edit the line distributionUrl, from 5.4 to 6.7

distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip  


Within the file android/app/build.gradle

Add the lines bellow

++ packagingOptions {
++        pickFirst 'lib/x86/libc++_shared.so'
++       pickFirst 'lib/x86_64/libc++_shared.so'
++        pickFirst 'lib/armeabi-v7a/libc++_shared.so'
++       pickFirst 'lib/arm64-v8a/libc++_shared.so'
++    }

    defaultConfig {
        applicationId "com.qonteofaces"
	minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
	versionCode 1
        versionName "1.0"
++        multiDexEnabled true
++        missingDimensionStrategy 'react-native-camera', 'general'
    }
